apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-services
  template:
    metadata:
      labels:
        app: broker-services
    spec:
      containers:
        - name: broker-services
          image: "zafei/broker-service:1.0.1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: broker-services
spec:
  selector:
    app: broker-services
  ports:
    - protocol: TCP
      name: main-port
      port: 8080
      targetPort: 8080
