apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-services
  template:
    metadata:
      labels:
        app: mail-services
    spec:
      containers:
        - name: mail-services
          image: "zafei/mail-service:1.0.0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MAIL_DOMAIN
              value: ""
            - name: MAIL_HOST
              value: "localhost"
            - name: MAIL_PORT
              value: "1025"
            - name: MAIL_ENCRYPTION
              value: "none"
            - name: MAIL_USERNAME
              value: ""
            - name: MAIL_PASSWORD
              value: ""
            - name: FROM_NAME
              value: "John Smith"
            - name: FROM_ADDRESS
              value: "john.smith@example.com"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mail-services
spec:
  selector:
    app: mail-services
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
